version: "3.8"

services:
  helios-explorer:
    container_name: helios-explorer-dev
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.dev
    ports:
      - "3000:3000"
